version: "2"

run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
  concurrency: 4

output:
  formats:
    tab:
      print-linter-name: true
      colors: true
  sort-order:
    - file
    - severity
    - linter

linters:
  default: all
  disable:
    - godox
    - tagliatelle
    - varnamelen
    - ireturn

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
          allow:
          - $gostd
          - github.com/alicebob/miniredis/v2
          - github.com/eser/ajan
          - github.com/getkin/kin-openapi/openapi3
          - github.com/go-faker/faker/v4
          - github.com/golang-jwt/jwt/v5
          - github.com/oklog/ulid/v2
          - github.com/rabbitmq/amqp091-go
          - github.com/redis/go-redis/v9
          - github.com/stretchr/testify
          - go.opentelemetry.io/otel
          - go.opentelemetry.io/contrib
          - golang.org/x/net/http/httpguts
          - google.golang.org/grpc
          - google.golang.org/grpc/reflection
          - google.golang.org/grpc/status
    revive:
      rules:
        - name: "var-naming"
          severity: warning
          disabled: true
          arguments:
            - ["ID", "HTTP", "JSON", "URI", "URL", "SLA", "RFC"] # AllowList
            - [] # DenyList
            - - upper-case-const: false
    varnamelen:
      ignore-names:
        - err
      ignore-decls:
        - ctx context.Context
        - t testing.T
        - i int
        - n int
        - const C
        - T any
        - w http.ResponseWriter
        - r *http.Request
        - w http.ResponseWriter
  exclusions:
    paths:
      - ops
      - tmp

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

issues:
  fix: true
