log-level: ""
all: True
dir: "{{.InterfaceDirRelative}}/../{{.PackageName}}_mock"
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mock"
filename: "{{.InterfaceName | snakecase}}_mock.go"
resolve-type-alias: False
issue-845-fix: True
packages:
  github.com/eser/ajan:
    config:
      recursive: True
