// Code generated by mockery v2.52.3. DO NOT EDIT.

package datafx_mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// SqlExecutor is an autogenerated mock type for the SqlExecutor type
type SqlExecutor struct {
	mock.Mock
}

type SqlExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *SqlExecutor) EXPECT() *SqlExecutor_Expecter {
	return &SqlExecutor_Expecter{mock: &_m.Mock}
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *SqlExecutor) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sql.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sql.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SqlExecutor_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type SqlExecutor_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *SqlExecutor_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *SqlExecutor_ExecContext_Call {
	return &SqlExecutor_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *SqlExecutor_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *SqlExecutor_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *SqlExecutor_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *SqlExecutor_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SqlExecutor_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sql.Result, error)) *SqlExecutor_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function with given fields: ctx, query
func (_m *SqlExecutor) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SqlExecutor_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type SqlExecutor_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *SqlExecutor_Expecter) PrepareContext(ctx interface{}, query interface{}) *SqlExecutor_PrepareContext_Call {
	return &SqlExecutor_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *SqlExecutor_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *SqlExecutor_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SqlExecutor_PrepareContext_Call) Return(_a0 *sql.Stmt, _a1 error) *SqlExecutor_PrepareContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SqlExecutor_PrepareContext_Call) RunAndReturn(run func(context.Context, string) (*sql.Stmt, error)) *SqlExecutor_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *SqlExecutor) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (*sql.Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SqlExecutor_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type SqlExecutor_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *SqlExecutor_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *SqlExecutor_QueryContext_Call {
	return &SqlExecutor_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *SqlExecutor_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *SqlExecutor_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *SqlExecutor_QueryContext_Call) Return(_a0 *sql.Rows, _a1 error) *SqlExecutor_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SqlExecutor_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...any) (*sql.Rows, error)) *SqlExecutor_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, query, args
func (_m *SqlExecutor) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// SqlExecutor_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type SqlExecutor_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *SqlExecutor_Expecter) QueryRowContext(ctx interface{}, query interface{}, args ...interface{}) *SqlExecutor_QueryRowContext_Call {
	return &SqlExecutor_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *SqlExecutor_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *SqlExecutor_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *SqlExecutor_QueryRowContext_Call) Return(_a0 *sql.Row) *SqlExecutor_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SqlExecutor_QueryRowContext_Call) RunAndReturn(run func(context.Context, string, ...any) *sql.Row) *SqlExecutor_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewSqlExecutor creates a new instance of SqlExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSqlExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *SqlExecutor {
	mock := &SqlExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
