// Code generated by mockery v2.52.3. DO NOT EDIT.

package datafx_mock

import mock "github.com/stretchr/testify/mock"

// TransactionFinalizer is an autogenerated mock type for the TransactionFinalizer type
type TransactionFinalizer struct {
	mock.Mock
}

type TransactionFinalizer_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionFinalizer) EXPECT() *TransactionFinalizer_Expecter {
	return &TransactionFinalizer_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with no fields
func (_m *TransactionFinalizer) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionFinalizer_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type TransactionFinalizer_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *TransactionFinalizer_Expecter) Commit() *TransactionFinalizer_Commit_Call {
	return &TransactionFinalizer_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *TransactionFinalizer_Commit_Call) Run(run func()) *TransactionFinalizer_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TransactionFinalizer_Commit_Call) Return(_a0 error) *TransactionFinalizer_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionFinalizer_Commit_Call) RunAndReturn(run func() error) *TransactionFinalizer_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with no fields
func (_m *TransactionFinalizer) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionFinalizer_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type TransactionFinalizer_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *TransactionFinalizer_Expecter) Rollback() *TransactionFinalizer_Rollback_Call {
	return &TransactionFinalizer_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *TransactionFinalizer_Rollback_Call) Run(run func()) *TransactionFinalizer_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TransactionFinalizer_Rollback_Call) Return(_a0 error) *TransactionFinalizer_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionFinalizer_Rollback_Call) RunAndReturn(run func() error) *TransactionFinalizer_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionFinalizer creates a new instance of TransactionFinalizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionFinalizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionFinalizer {
	mock := &TransactionFinalizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
