// Code generated by mockery v2.52.3. DO NOT EDIT.

package datafx_mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// TransactionStarter is an autogenerated mock type for the TransactionStarter type
type TransactionStarter struct {
	mock.Mock
}

type TransactionStarter_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionStarter) EXPECT() *TransactionStarter_Expecter {
	return &TransactionStarter_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *TransactionStarter) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionStarter_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type TransactionStarter_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *TransactionStarter_Expecter) BeginTx(ctx interface{}, opts interface{}) *TransactionStarter_BeginTx_Call {
	return &TransactionStarter_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *TransactionStarter_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *TransactionStarter_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *TransactionStarter_BeginTx_Call) Return(_a0 *sql.Tx, _a1 error) *TransactionStarter_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionStarter_BeginTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *TransactionStarter_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionStarter creates a new instance of TransactionStarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionStarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionStarter {
	mock := &TransactionStarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
