// Code generated by mockery v2.52.3. DO NOT EDIT.

package httpfx_mock

import (
	httpfx "github.com/eser/ajan/httpfx"
	mock "github.com/stretchr/testify/mock"
)

// Middleware is an autogenerated mock type for the Middleware type
type Middleware struct {
	mock.Mock
}

type Middleware_Expecter struct {
	mock *mock.Mock
}

func (_m *Middleware) EXPECT() *Middleware_Expecter {
	return &Middleware_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *Middleware) Execute() httpfx.Handler {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 httpfx.Handler
	if rf, ok := ret.Get(0).(func() httpfx.Handler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpfx.Handler)
		}
	}

	return r0
}

// Middleware_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Middleware_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *Middleware_Expecter) Execute() *Middleware_Execute_Call {
	return &Middleware_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *Middleware_Execute_Call) Run(run func()) *Middleware_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Middleware_Execute_Call) Return(_a0 httpfx.Handler) *Middleware_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Middleware_Execute_Call) RunAndReturn(run func() httpfx.Handler) *Middleware_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMiddleware creates a new instance of Middleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *Middleware {
	mock := &Middleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
