// Code generated by "stringer -type ConnectionState -trimprefix ConnectionState"; DO NOT EDIT.

package connfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectionStateUnknown-0]
	_ = x[ConnectionStateConnected-1]
	_ = x[ConnectionStateDisconnected-2]
	_ = x[ConnectionStateError-3]
	_ = x[ConnectionStateReconnecting-4]
}

const _ConnectionState_name = "UnknownConnectedDisconnectedErrorReconnecting"

var _ConnectionState_index = [...]uint8{0, 7, 16, 28, 33, 45}

func (i ConnectionState) String() string {
	if i < 0 || i >= ConnectionState(len(_ConnectionState_index)-1) {
		return "ConnectionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionState_name[_ConnectionState_index[i]:_ConnectionState_index[i+1]]
}
